apiVersion: clustertemplate.openshift.io/v1alpha1
kind: ClusterTemplateInstance
metadata:
  namespace: <value>
  name: <value>
spec:
  clusterTemplateRef: cluster-template-example
  values:
    - name: prop1
      value: sampletemplateinstance.com
      # type: string
      # description: Base DNS domain of the cluster
    - name: APIPublishingStrategy
      value: LoadBalancer
      # description: API Publishing strategy - can be LoadBalancer or NodePort
    - name: ocpVersion
      value: 4.11.9-multi
      # description: OCP version to be used
    - name: ocpArch
      value: x86_64
      # description: OCP arch to be used
    - name: sshPublicKey
      value: <value>
      # description: SSH public key to be injected into all cluster node sshd servers
      # A default value is defined in a secret
    - name: clusterSetupSecretProp1
      value: <value>
      clusterSetup: setup1
      # description: clusterSetupSecretProp1
      # A default value is defined in a secret
    - name: prop1
      value: <value>
      clusterSetup: setup2
      # type: string
      # description: prop for testing duplicated property name
