FROM registry.redhat.io/ubi9/nodejs-20-minimal@sha256:754490f85d24ed528afaf986fc2df2748fd75e6a2591885f1c84fe267559e6e4 AS builder

USER root
ENV NPM_CONFIG_NODEDIR=/usr

WORKDIR /app
COPY . .

# Running installs concurrently fails on aarch64
RUN npm ci --omit=optional --unsafe-perm --ignore-scripts --maxsockets=5 --network-concurrency=3
RUN cd backend && npm ci --omit=optional  --unsafe-perm --ignore-scripts --maxsockets=5 --network-concurrency=3
RUN cd frontend && npm ci --legacy-peer-deps --unsafe-perm --ignore-scripts --maxsockets=5 --network-concurrency=3
RUN npm run build:backend
RUN cd frontend && npm run build:plugin:acm --maxsockets=5 --network-concurrency=3

# Remove build-time dependencies before packaging
RUN cd backend && npm ci --omit=optional --only=production --unsafe-perm --ignore-scripts --maxsockets=5 --network-concurrency=3

FROM registry.redhat.io/ubi9/nodejs-20-minimal@sha256:754490f85d24ed528afaf986fc2df2748fd75e6a2591885f1c84fe267559e6e4

WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/backend/node_modules ./node_modules
COPY --from=builder /app/backend/backend.mjs ./
COPY --from=builder /app/frontend/plugins/acm/dist ./public/plugin
USER 1001
CMD ["node", "backend.mjs"]

LABEL com.redhat.component="console-container" \
      url="https://github.com/stolostron/console" \
      name="rhacm2/console-rhel9" \
      summary="console" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images" \
      io.k8s.display-name="console" \
      maintainer="['acm-component-maintainers@redhat.com']" \
      description="console" \
      io.k8s.description="console"
