FROM registry.redhat.io/ubi9/nodejs-20-minimal@sha256:ae1c763a0e806ab4867aaf8421e8883d05f30fe2812f95b99dae60424a571e29 AS builder

USER root
ENV NPM_CONFIG_NODEDIR=/usr

WORKDIR /app
COPY . .

# Running installs concurrently fails on aarch64
RUN npm ci --omit=optional --unsafe-perm --ignore-scripts
RUN cd backend && npm ci --omit=optional  --unsafe-perm
RUN cd frontend && npm ci --legacy-peer-deps --unsafe-perm
RUN npm run build:backend
RUN cd frontend && npm run build:plugin:acm

# Remove build-time dependencies before packaging
RUN cd backend && npm ci --omit=optional --only=production --unsafe-perm

FROM registry.redhat.io/ubi9/nodejs-20-minimal@sha256:ae1c763a0e806ab4867aaf8421e8883d05f30fe2812f95b99dae60424a571e29

WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/backend/node_modules ./node_modules
COPY --from=builder /app/backend/backend.mjs ./
COPY --from=builder /app/frontend/plugins/acm/dist ./public/plugin
USER 1001
CMD ["node", "backend.mjs"]

LABEL com.redhat.component="console-container" \
      name="rhacm2/console-rhel9" \
      summary="console" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images" \
      io.k8s.display-name="console" \
      maintainer="['acm-component-maintainers@redhat.com']" \
      description="console" \
      io.k8s.description="console"
