# Copyright Contributors to the Open Cluster Management project
ARG NODE_BASE=registry.redhat.io/ubi9/nodejs-24-minimal:latest
ARG RUNTIME_BASE=registry.redhat.io/ubi9/ubi-minimal:latest
ARG GO_BASE=registry.redhat.io/openshift/golang-builder:golang-builder-v1.26-rhel9

FROM registry.redhat.io/ubi9/ubi:latest AS crypto-policy
RUN update-crypto-policies --set DEFAULT:PQ

FROM ${NODE_BASE} as build-base
USER root
ENV NPM_CONFIG_IGNORE_SCRIPTS=true

FROM build-base as dynamic-plugin
WORKDIR /app/frontend
COPY ./frontend .
# Optimization of copying only package.json and package-lock.json does not work because of workspace packages
RUN npm ci --legacy-peer-deps
RUN npm run build:plugin:acm

FROM ${GO_BASE} as go-backend
WORKDIR /src
COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download
COPY ./backend .
RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -o /console ./cmd/console

FROM ${RUNTIME_BASE}
COPY --from=crypto-policy /etc/crypto-policies /etc/crypto-policies
WORKDIR /app
ENV NODE_ENV production
ENV PUBLIC_FOLDER=/app/public
COPY --from=go-backend /console ./console
COPY --from=dynamic-plugin /app/frontend/plugins/acm/dist ./public/plugin
COPY ./scripts/console-entrypoint.sh ./console-entrypoint.sh
RUN chmod 755 /app/console-entrypoint.sh /app/console
USER 1001
CMD ["/app/console-entrypoint.sh"]

LABEL com.redhat.component="console-container" \
      cpe="cpe:/a:redhat:acm:5.1::el9" \
      url="https://github.com/stolostron/console" \
      name="rhacm2/console-rhel9" \
      summary="console" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images" \
      io.k8s.display-name="console" \
      maintainer="['acm-component-maintainers@redhat.com']" \
      description="console" \
      io.k8s.description="console"
