FROM registry.redhat.io/ubi9/nodejs-20-minimal@sha256:39e45fb57afe2da2a571f1f4be5c4a1d24990c24a1c7a523ef187699a9b57c73 AS builder

USER root
ENV NPM_CONFIG_NODEDIR=/usr

WORKDIR /app
COPY . .

# Running installs concurrently fails on aarch64
RUN npm ci --omit=optional --unsafe-perm --ignore-scripts
RUN cd backend && npm ci --omit=optional  --unsafe-perm
RUN cd frontend && npm ci --legacy-peer-deps --unsafe-perm
RUN npm run build:backend
RUN cd frontend && npm run build:plugin:mce

# Remove build-time dependencies before packaging
RUN cd backend && npm ci --omit=optional --only=production --unsafe-perm

FROM registry.redhat.io/ubi9/nodejs-20-minimal@sha256:39e45fb57afe2da2a571f1f4be5c4a1d24990c24a1c7a523ef187699a9b57c73

WORKDIR /app
ENV NODE_ENV production
COPY --from=builder /app/backend/node_modules ./node_modules
COPY --from=builder /app/backend/backend.mjs ./
COPY --from=builder /app/frontend/plugins/mce/dist ./public/plugin
USER 1001
CMD ["node", "backend.mjs"]

LABEL com.redhat.component="multicluster-engine-console-mce-container" \
      name="multicluster-engine/console-mce-rhel9" \
      summary="multicluster-engine-console-mce" \
      io.openshift.expose-services="" \
      io.openshift.tags="data,images" \
      io.k8s.display-name="multicluster-engine-console-mce" \
      maintainer="['acm-component-maintainers@redhat.com']" \
      description="multicluster-engine-console-mce" \
      io.k8s.description="multicluster-engine-console-mce"
