# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: install
install:
	npm ci --omit=optional
	npm run postinstall

.PHONY: build
build:
	npm run build:frontend
	npm run build:backend

.PHONY: check
check:
	npx concurrently --kill-others-on-fail npm:copyright:check npm:check:frontend npm:check:backend -c green,blue,magenta

.PHONY: lint
lint:
	npx concurrently --kill-others-on-fail npm:lint:frontend npm:lint:backend -c green,blue

.PHONY: unit-tests
unit-tests:
	if [ ! -d "test-output" ]; then \
		mkdir test-output; \
	fi
	npm run test:frontend -- --maxWorkers=2
	npm run test:backend
