apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    name: policy-with-2-placement-rules
    namespace: test
    annotations:
        policy.open-cluster-management.io/standards: NIST-CSF
        policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
        policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
    remediationAction: inform
    disabled: false
    policy-templates:
        - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                  name: policy-with-2-placement-rules
              spec:
                  remediationAction: inform
                  severity: low
                  namespaceSelector:
                      exclude:
                          - kube-*
                      include:
                          - default
                  object-templates:
                      - complianceType: musthave
                        objectDefinition:
                            kind: Namespace
                            apiVersion: v1
                            metadata:
                                name: test
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: policy-with-2-placement-rules-1
    namespace: test
placementRef:
    name: policy-with-2-placement-rules-1
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: policy-with-2-placement-rules
      kind: Policy
      apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: policy-with-2-placement-rules-1
    namespace: test
spec:
    clusterConditions:
        - status: 'True'
          type: ManagedClusterConditionAvailable
    clusterSelector:
        matchExpressions:
            - key: local-cluster
              operator: In
              values:
                  - 'true'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: policy-with-2-placement-rules-2
    namespace: test
placementRef:
    name: policy-with-2-placement-rules-2
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: policy-with-2-placement-rules
      kind: Policy
      apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: policy-with-2-placement-rules-2
    namespace: test
spec:
    clusterConditions:
        - status: 'True'
          type: ManagedClusterConditionAvailable
    clusterSelector:
        matchExpressions:
            - key: abc
              operator: In
              values:
                  - '123'
