apiVersion: policy.open-cluster-management.io/v1
kind: PolicySet
metadata:
    name: policy-set-with-2-placement-rules
    namespace: test
spec:
    description: Policy set with a two PlacementRules and PlacementBindings.
    policies:
        - policy-set-with-2-placement-rules-policy-1
        - policy-set-with-2-placement-rules-policy-2
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: policy-set-with-2-placement-rules-1
    namespace: test
placementRef:
    name: policy-set-with-2-placement-rules-1
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: policy-set-with-2-placement-rules
      kind: PolicySet
      apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: policy-set-with-2-placement-rules-1
    namespace: test
spec:
    clusterConditions:
        - status: 'True'
          type: ManagedClusterConditionAvailable
    clusterSelector:
        matchExpressions:
            - key: local-cluster
              operator: In
              values:
                  - 'true'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: policy-set-with-2-placement-rules-2
    namespace: test
placementRef:
    name: policy-set-with-2-placement-rules-2
    kind: PlacementRule
    apiGroup: apps.open-cluster-management.io
subjects:
    - name: policy-set-with-2-placement-rules
      kind: PolicySet
      apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: policy-set-with-2-placement-rules-2
    namespace: test
spec:
    clusterConditions:
        - status: 'True'
          type: ManagedClusterConditionAvailable
    clusterSelector:
        matchExpressions:
            - key: abc
              operator: In
              values:
                  - '123'
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    name: policy-set-with-2-placement-rules-policy-1
    namespace: test
    annotations:
        policy.open-cluster-management.io/standards: NIST-CSF
        policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
        policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
    remediationAction: inform
    disabled: false
    policy-templates:
        - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                  name: policy-set-with-2-placement-rules-policy-1
              spec:
                  remediationAction: inform
                  severity: low
                  namespaceSelector:
                      exclude:
                          - kube-*
                      include:
                          - default
                  object-templates:
                      - complianceType: musthave
                        objectDefinition:
                            kind: Namespace
                            apiVersion: v1
                            metadata:
                                name: test
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    name: policy-set-with-2-placement-rules-policy-2
    namespace: test
    annotations:
        policy.open-cluster-management.io/standards: NIST-CSF
        policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
        policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
    remediationAction: inform
    disabled: false
    policy-templates:
        - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                  name: policy-set-with-2-placement-rules-policy-2
              spec:
                  remediationAction: inform
                  severity: low
                  namespaceSelector:
                      exclude:
                          - kube-*
                      include:
                          - default
                  object-templates:
                      - complianceType: musthave
                        objectDefinition:
                            kind: Namespace
                            apiVersion: v1
                            metadata:
                                name: test
