apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    name: policy-with-2-placements
    namespace: test
    annotations:
        policy.open-cluster-management.io/standards: NIST-CSF
        policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
        policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
    remediationAction: inform
    disabled: false
    policy-templates:
        - objectDefinition:
              apiVersion: policy.open-cluster-management.io/v1
              kind: ConfigurationPolicy
              metadata:
                  name: policy-with-2-placements
              spec:
                  remediationAction: inform
                  severity: low
                  namespaceSelector:
                      exclude:
                          - kube-*
                      include:
                          - default
                  object-templates:
                      - complianceType: musthave
                        objectDefinition:
                            kind: Namespace
                            apiVersion: v1
                            metadata:
                                name: test
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
    name: policy-with-2-placements-1
    namespace: test
spec:
    predicates:
        - requiredClusterSelector:
              labelSelector:
                  matchExpressions:
                      - key: local-cluster
                        operator: In
                        values:
                            - 'true'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: policy-with-2-placements-1
    namespace: test
placementRef:
    name: policy-with-2-placements-1
    kind: Placement
    apiGroup: cluster.open-cluster-management.io
subjects:
    - name: policy-with-2-placements
      kind: PolicySet
      apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
    name: policy-with-2-placements-2
    namespace: test
spec:
    clusterSets:
        - cluster-set
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: policy-with-2-placements-2
    namespace: test
placementRef:
    name: policy-with-2-placements-2
    kind: Placement
    apiGroup: cluster.open-cluster-management.io
subjects:
    - name: policy-with-2-placements
      kind: PolicySet
      apiGroup: policy.open-cluster-management.io
