apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: operator-policy-install-name
  namespace: open-cluster-management-global-set
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            name:
            channel:
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions:
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: compliance-api-install
  namespace: open-cluster-management-global-set
spec: {}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: compliance-api-install
placementRef:
  name: compliance-api-install
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: compliance-api-install
    apiGroup: policy.open-cluster-management.io
    kind: Policy
