export const REQUEST_STATUS = {
    INCEPTION: 'INCEPTION',
    DONE: 'DONE',
    IN_PROGRESS: 'IN_PROGRESS',
    ERROR: 'ERROR',
    NOT_FOUND: 'NOT_FOUND',
    CLUSTER_OFFLINE: 'CLUSTER_OFFLINE',
}
