name: Publish multicluster-sdk

on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: "Version increment type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    defaults:
      run:
        working-directory: frontend/packages/multicluster-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tests
        run: npm run test

      - name: Run linting
        run: npm run lint

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"

      - name: Update package version
        id: version_update
        run: |
          NEW_VERSION=$(npm version ${{ inputs.version_increment }} --no-git-tag-version)
          # Strip the 'v' prefix from the version
          VERSION_CLEAN=${NEW_VERSION#v}
          TAG="multicluster-sdk-$VERSION_CLEAN"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION_CLEAN" >> $GITHUB_ENV
          echo "Updated to version: $VERSION_CLEAN (tag: $TAG)"

      - name: Build package
        run: npm run build

      - name: Test publish (dry run)
        run: npm publish --dry-run

      - name: Add and commit version update
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Release ${{ env.TAG }} [skip ci]
          tag: ${{ env.TAG }}
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
