name: Pull Request
on:
    pull_request:
        paths:
          - './frontend/packages/react-form-wizard/**'
        branches:
        - main
jobs:
  
    pull-request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  cache: 'npm'
            - run: npm ci
              working-directory: ./frontend/packages/react-form-wizard
            - run: npm test
              working-directory: ./frontend/packages/react-form-wizard